# Generated by Django 4.0.3 on 2022-04-03 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_fashion_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='place',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
