# Generated by Django 4.0.3 on 2022-04-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_fashion_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fashion',
        ),
    ]
