# Generated by Django 4.0.3 on 2022-04-03 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_delete_fashion'),
    ]

    operations = [
        migrations.CreateModel(
            name='fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('place', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('shirt_color', models.CharField(max_length=20)),
                ('shirt_type', models.CharField(max_length=20)),
                ('pant_color', models.CharField(max_length=20)),
                ('pant_type', models.CharField(max_length=20)),
                ('accessories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
    ]
