# Generated by Django 4.0.3 on 2022-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='gender',
            field=models.CharField(default='unisex', max_length=6),
        ),
    ]
